1-module\1-task
js-tasks-ru/jsbasic-20210420_sergey75 pull request #2
Opened 2021-04-21 08:20 UTC by SergeySh3

Привет. Написал код для вычисления факториала. Всё работает, но npm test выдает такие ошибки:

× факториал 0 равен 1

    Error: Expected undefined to equal 1.
        at <Jasmine>
        at UserContext.<anonymous> (1-module/1-task/task.test.js:3:26)
        at <Jasmine>

    × факториал 5 равен 120

    Error: Expected undefined to equal 120.
        at <Jasmine>
        at UserContext.<anonymous> (1-module/1-task/task.test.js:15:26)
        at <Jasmine>

2021-04-21 08:20 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-04-21 17:27 UTC, SinimaWath requested changes

2021-04-21 17:27 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  alert (result);
по условию задачи, нужно выводить не через alert. А вернуть значение из функции, нужно это сделать через `return`

2021-04-21 17:27 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    }
Эту проверку - можно и нужно унести на начало функции. Если у тебя n == 1 || n == 0, то тебе даже не нужно заходить в цикл

2021-04-21 18:21 UTC, SergeySh3 commented
Всё исправил, прошел npm test. Спасибо

2021-04-25 11:26 UTC, SinimaWath requested changes

2021-04-25 11:26 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  return result;
В этой конструкции else лишний:

```
if () {
  return ...
}

for (...) {
...
}
```

2021-04-25 11:27 UTC, SinimaWath commented on 1-module/1-task/index.js
> +factorial(5);
И давай все таки уберем проверки из коммита

2021-04-25 13:50 UTC, SergeySh3 commented
Проверь пожалуйста

2021-04-25 14:33 UTC, SinimaWath approved these changes
Все ок :)

2021-04-25 14:34 UTC, merged